Vagrant.configure(2) do |config|

    config.vm.box = "bento/ubuntu-18.04"

    # Create a forwarded port
    config.vm.network "forwarded_port", guest: 85, host: 8089

    # configuration for virtualbox
    config.vm.provider :virtualbox do |v|
        v.name = "Bionic64" #setup the vm name
        v.gui = false # show GUI or not.
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"] #use no more than 50% CPU on host machine
        v.memory = '3096' # machine ram, Elastic needs about 2GB
        v.customize ["modifyvm", :id, "--vram", "64"]  #ram for virtual graphics card

        # Enable the use of hardware virtualization extensions (Intel VT-x or AMD-V) in the processor of your host system
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
    end

end
