# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  # Create a forwarded port
  config.vm.network "public_network",ip: "192.168.1.108", bridge: "wlp3s0"

  # Create a private network. In VirtualBox, this is a Host-Only network
  #config.vm.network "private_network", ip: "192.168.33.10"
  # pass files
  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    # Hide the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end


  # Provision the machine with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y crowbar
    sudo apt-get install -y terminator
    if [ -f /home/vagrant/workspace/cs/01_mac_address_changer/README.md ] ; then
    sudo rm -R /home/vagrant/workspace/cs/
    fi
  SHELL
  config.vm.provision "file", source: "~/workspace/cs", destination: "/home/vagrant/workspace/cs"

end
